services:
  user_service:
    image: user_service
    tty: true

    ports:
      - "80:80"
    volumes:
      - .:/code
    env_file:
      - .env

  redis:
    image: redis
    ports:
      - "6379:6379"

